BankMVCApp/BankMVCApp/Models/CustomerDetailViewModel.cs
using BankDB.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BankMVCApp.Models
{
    public class CustomerDetailViewModel
    {
        //Customer info
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? CustomerSince { get; set; }
        //Address Details
        public List<Address> Addresses { get; set; }
        //Acctont Details
        public List<Account> Accounts { get; set; }
    }
}

BankMVCApp/BankMVCApp/Controllers/AccountLoginController.cs
using BankDB.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace BankMVCApp.Controllers
{
    public class AccountLoginController : Controller
    {
        [HttpGet]
        // GET: AccountLogin
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogOn(UserLogin model)
        {
            bool isValidated = false;
            string errorMessage = string.Empty;
            try
            {
                //Authenticate against our DB
                BankDBEntities dBEntities = new BankDBEntities();
                var data = dBEntities.UserLogins
                    .Where(x => x.UserName == model.UserName && x.Password == model.Password).FirstOrDefault();
                if (data != null)
                {
                    isValidated = true;
                }
                if (isValidated)
                {
                    FormsAuthentication.SetAuthCookie(model.UserName, true);
                    return RedirectToAction("Index", "Bank");
                }
                else
                {
                    errorMessage = "Unable to validate. Authentication failed!";
                }
            }
            catch (Exception ex)
            {
                errorMessage = ex.Message;
            }
            ViewBag.AuthMessage = errorMessage;
            return View("Index");
        }

        public ActionResult LogOff()
        {
            Session.Abandon();
            FormsAuthentication.SignOut();
            return View("Index");
        }
    }
}

BankMVCApp/BankMVCApp/Controllers/BankController.cs
using BankDB.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BankMVCApp.Controllers
{
    [Authorize]
    [BankErrorHandler]
    public class BankController : Controller
    {
        //private List<Account> listOfAccounts = new List<Account>();
        public BankController()
        {            
            //listOfAccounts.Add(new Account { AccountNumber = "456565", AccountType = "Checking", Balance = 5000000 });
            //listOfAccounts.Add(new Account { AccountNumber = "998898", AccountType = "Saving", Balance = 6889888 });
            //listOfAccounts.Add(new Account { AccountNumber = "99099", AccountType = "Checking", Balance = 5000000 });
            //listOfAccounts.Add(new Account { AccountNumber = "778777", AccountType = "Saving", Balance = 6889888 });
            //listOfAccounts.Add(new Account { AccountNumber = "77877", AccountType = "Saving", Balance = 5000000 });
            //listOfAccounts.Add(new Account { AccountNumber = "88987", AccountType = "Checking", Balance = 6889888 });
            //listOfAccounts.Add(new Account { AccountNumber = "77876", AccountType = "Saving", Balance = 5000000 });
        }
        // GET: Bank
        [BankErrorHandler]
        public ActionResult Index()
        {
            BankDBEntities bankDBEntities = new BankDBEntities();
            if (TempData["CreateMessage"] != null)
            {
                ViewBag.Message = TempData["CreateMessage"].ToString();
            }
            return View(bankDBEntities.Accounts);
        }

        // GET: Bank/Details/5
        public ActionResult Details(string id)
        {            
            return View();
        }

        // GET: Bank/Create
        public ActionResult Create()
        {
            BankDB.Model.BankDBEntities bankDBEntities = new BankDB.Model.BankDBEntities();
            var accountTypes = new List<SelectListItem>();
            foreach (var item in bankDBEntities.AccountTypes)
            {
                var drpItem = new SelectListItem { Text = item.AccountType1, Value = item.AccountTypeId.ToString() };
                accountTypes.Add(drpItem);
            }            
            ViewBag.AccountItemList = accountTypes;
            return View();
        }

        // POST: Bank/Create
        [HttpPost]
        public ActionResult Create(Account account)
        {
            BankDBEntities bankDBEntities = new BankDB.Model.BankDBEntities();
            try
            {
                
                bankDBEntities.Accounts.Add(account);
                bankDBEntities.SaveChanges();
                TempData["CreateMessage"] = $"Account {account.AccountNumber} was successfully saved to database!";
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                var accountTypes = new List<SelectListItem>();
                foreach (var item in bankDBEntities.AccountTypes)
                {
                    var drpItem = new SelectListItem { Text = item.AccountType1, Value = item.AccountTypeId.ToString() };
                    accountTypes.Add(drpItem);
                }
                ViewBag.AccountItemList = accountTypes;
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: Bank/Edit/5
        public ActionResult Edit(string id)
        {            
            return View();
        }

        // POST: Bank/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Bank/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Bank/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BankMVCApp/BankMVCApp/Views/Shared/_CustomerDetail.cshtml
@model BankMVCApp.Models.CustomerDetailViewModel
<div>
    <table class="table">
        <tr class="">
            <td class="table-bordered">
                <div>
                    <h4>Customer Info:</h4>
                    <div>
                        <div>
                            @Html.LabelFor(x => x.FirstName)
                            @Html.DisplayFor(x => x.FirstName)
                        </div>
                        <div>
                            @Html.LabelFor(x => x.LastName)
                            @Html.DisplayFor(x => x.LastName)
                        </div>
                        <div>
                            @Html.LabelFor(x => x.CustomerSince)
                            @Html.DisplayFor(x => x.CustomerSince)
                        </div>
                    </div>
                </div>
            </td>
            <td class="table-bordered">
                <div>
                    <h4>Address Details:</h4>
                    <div>
                        @foreach (var item in Model.Addresses)
                        {
                            <h2>@item.AddressType</h2>
                            <div>
                                @Html.DisplayFor(itm => item.StreetName)
                            </div>
                            <div>
                                @Html.DisplayFor(itm => item.City)
                                @Html.DisplayFor(itm => item.State)
                                @Html.DisplayFor(itm => item.Zip)
                            </div>
                        }
                    </div>
                </div>
            </td>
            <td class="table-bordered">
                <div>
                    <h4>Account Details:</h4>
                    <div>
                        @foreach (var item in Model.Accounts)
                        {
                            <h2>@item.AccountType.AccountType1</h2>
                            <div>
                                @Html.LabelFor(x => item.AccountNumber)
                                @Html.DisplayFor(itm => item.AccountNumber)
                            </div>
                            <div>
                                @Html.LabelFor(x => item.AvailableBalance)
                                @Html.DisplayFor(itm => item.AvailableBalance)
                                @Html.ActionLink("Create","Create","Transaction", new { id=item.AccountId})
                            </div>
                        }
                    </div>                   
                </div>
            </td>
        </tr>
    </table>
</div>

BankMVCApp/BankMVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Accounts", "Index", "Bank")</li>
                </ul>
            </div>
            <div>
                @Html.Partial("_logOnPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>    
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BankMVCApp/BankMVCApp/Views/Shared/_logOnPartial.cshtml
@if (Request.IsAuthenticated)
{
    @Html.ActionLink("LogOff", "LogOff", "AccountLogin")
}
else
{
    @Html.ActionLink("Login", "Index", "AccountLogin")
}